#pragma once

#include <string_view>

namespace sbeasy::detail {

inline constexpr std::string_view agent_interface_html = R"HTML(<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>sb-easy Agent</title>
  <style>
    :root{--bg:#171820;--sidebar:#242631;--surface:#20222c;--surface-2:#282b37;--surface-3:#303440;--line:#393d4a;--text:#f5f6fa;--muted:#9b9fab;--blue:#4d8ff7;--blue-soft:#283e64;--green:#66d17a;--orange:#f5a742;--red:#f06b78;--purple:#a982ed;--shadow:0 14px 35px #08091033}
    *{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;overflow:hidden}button,input,textarea{font:inherit}.app{height:100%;display:grid;grid-template-columns:238px minmax(0,1fr)}
    .sidebar{background:var(--sidebar);border-right:1px solid #30323c;display:flex;flex-direction:column;min-height:0;padding:24px 15px 18px}.brand{display:flex;align-items:center;gap:12px;padding:0 10px 25px}.brand-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,#5b9cff,#3d75d7);display:grid;place-items:center;box-shadow:0 9px 24px #3978df45}.brand-mark svg{width:22px;height:22px}.brand-name{font-size:17px;font-weight:760;letter-spacing:-.3px}.brand-meta{font-size:11px;color:var(--muted);margin-top:1px}
    .nav{display:grid;gap:7px}.nav-button{width:100%;display:flex;align-items:center;gap:13px;border:0;border-radius:10px;padding:11px 13px;background:transparent;color:#c1c4cd;cursor:pointer;text-align:left;font-weight:620;transition:.15s}.nav-button svg{width:19px;height:19px;opacity:.86}.nav-button:hover{background:#2d303b;color:#fff}.nav-button.active{background:#345a91;color:#fff;box-shadow:inset 0 0 0 1px #4777b9}.nav-spacer{height:7px}.sidebar-bottom{margin-top:auto;border-top:1px solid var(--line);padding:16px 9px 0}.node-line{display:flex;align-items:center;gap:9px}.node-dot{width:9px;height:9px;border-radius:50%;background:var(--muted)}.node-dot.online{background:var(--green);box-shadow:0 0 12px #66d17a88}.node-name{font-weight:700}.node-caption{font-size:11px;color:var(--muted)}.mini-traffic{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.mini-stat{padding:9px;border-radius:9px;background:#1d1f28;color:var(--muted);font-size:11px}.mini-stat b{display:block;color:#e9ebf1;font-size:12px;margin-top:2px}.logout{width:100%;border:0;background:transparent;color:var(--muted);padding:10px;margin-top:8px;border-radius:9px;cursor:pointer}.logout:hover{background:#30333e;color:#fff}
    .workspace{min-width:0;min-height:0;display:flex;flex-direction:column}.topbar{height:82px;flex:0 0 82px;background:#252731;border-bottom:1px solid #30333e;display:flex;align-items:center;justify-content:space-between;padding:0 28px}.page-title{font-size:22px;font-weight:760;letter-spacing:-.5px}.page-subtitle{font-size:12px;color:var(--muted);margin-top:2px}.top-actions{display:flex;align-items:center;gap:10px}.status-pill{display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:#1e2029;color:#c8cbd4;border-radius:999px;padding:8px 12px}.status-pill .node-dot{width:8px;height:8px}.icon-button,.button{border:1px solid var(--line);background:var(--surface-2);color:var(--text);border-radius:9px;padding:8px 12px;cursor:pointer;font-weight:650;transition:.15s}.icon-button{width:38px;height:38px;padding:0;display:grid;place-items:center}.icon-button svg{width:17px;height:17px}.icon-button:hover,.button:hover{border-color:#5777a8;background:#303847}.button.primary{background:var(--blue);border-color:var(--blue);color:#fff}.button.danger{color:#ffadb5}.button:disabled{opacity:.5;cursor:wait}.content{overflow:auto;padding:22px 24px 45px}.page{display:none;max-width:1260px;margin:0 auto}.page.active{display:block}
    .grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:15px}.card{background:var(--surface);border:1px solid #30333e;border-radius:13px;box-shadow:var(--shadow);overflow:hidden}.card-pad{padding:18px}.card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 17px;border-bottom:1px solid var(--line)}.card-title{display:flex;align-items:center;gap:10px;font-size:15px;font-weight:750}.card-title-icon{width:31px;height:31px;border-radius:8px;background:var(--blue-soft);color:var(--blue);display:grid;place-items:center}.card-title-icon svg{width:17px;height:17px}.card-note{font-size:12px;color:var(--muted)}
    .hero{grid-column:span 7}.sync{grid-column:span 5}.hero-body{padding:20px;display:flex;align-items:center;justify-content:space-between;gap:18px}.hero-state{display:flex;gap:14px;align-items:center}.hero-icon{width:54px;height:54px;border-radius:15px;background:#244d3a;color:var(--green);display:grid;place-items:center}.hero-icon svg{width:29px;height:29px}.hero-icon.offline{background:#4a2c34;color:var(--red)}.hero-label{color:var(--muted);font-size:12px}.hero-value{font-size:20px;font-weight:780;margin-top:2px}.hero-proxy{text-align:right;max-width:46%}.hero-proxy strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.type-chip,.tag-chip{display:inline-flex;border:1px solid #555a68;border-radius:999px;color:#b8bbc5;padding:2px 8px;font-size:11px;margin-top:6px}.sync-list{padding:13px 17px;display:grid;gap:12px}.sync-row{display:grid;grid-template-columns:100px minmax(0,1fr);gap:10px;align-items:center}.sync-row span{color:var(--muted);font-size:12px}.sync-row b{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sync-row code{font-size:11px;color:#a9c9ff}
    .metrics{grid-column:span 12;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px}.metric{background:var(--surface);border:1px solid #30333e;border-radius:12px;padding:15px 16px;display:flex;align-items:center;gap:13px}.metric-icon{width:39px;height:39px;border-radius:10px;display:grid;place-items:center}.metric-icon svg{width:20px;height:20px}.metric-icon.up{color:var(--orange);background:#4a3928}.metric-icon.down{color:var(--blue);background:#263b5d}.metric-icon.conn{color:var(--green);background:#263f35}.metric-icon.total{color:var(--purple);background:#3a304e}.metric-label{font-size:11px;color:var(--muted)}.metric-value{font-size:18px;font-weight:770;margin-top:2px}.traffic{grid-column:span 8}.operations{grid-column:span 4}.chart-wrap{height:225px;padding:14px 16px 8px;position:relative}.chart-wrap canvas{width:100%;height:100%}.chart-legend{position:absolute;right:19px;top:16px;display:flex;gap:13px;color:var(--muted);font-size:11px}.legend-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:5px}.operation-list{padding:15px;display:grid;gap:10px}.operation{border:1px solid var(--line);background:#272a34;border-radius:10px;padding:12px;display:flex;align-items:center;justify-content:space-between;gap:9px}.operation strong{font-size:13px}.operation small{display:block;color:var(--muted);font-size:11px;margin-top:2px}.error-banner{grid-column:span 12;background:#3b252c;border:1px solid #70404a;color:#ffc1c8;border-radius:11px;padding:11px 14px;display:none}.error-banner.show{display:block}
    .section-toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:15px}.section-copy h2{font-size:19px;margin:0}.section-copy p{color:var(--muted);margin:3px 0 0;font-size:12px}.search{width:min(310px,45vw);border:1px solid var(--line);border-radius:9px;background:var(--surface);color:var(--text);padding:9px 12px;outline:none}.search:focus{border-color:var(--blue)}.proxy-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.proxy-card{background:var(--surface);border:1px solid #30333e;border-radius:12px;padding:15px;min-width:0;transition:.15s}.proxy-card:hover{transform:translateY(-1px);border-color:#4b5364}.proxy-card.current{border-color:#4f8ce8;box-shadow:inset 0 0 0 1px #4f8ce855}.proxy-top{display:flex;align-items:center;justify-content:space-between;gap:10px}.proxy-avatar{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:#2c3f60;color:#79abfa;font-weight:800}.proxy-name{font-weight:720;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:13px}.proxy-meta{display:flex;align-items:center;justify-content:space-between;margin-top:9px;color:var(--muted);font-size:11px}.current-mark{color:var(--green);font-weight:700}.empty{grid-column:1/-1;border:1px dashed var(--line);border-radius:12px;padding:45px;text-align:center;color:var(--muted)}
    .settings-layout{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:15px}.form-card{background:var(--surface);border:1px solid #30333e;border-radius:13px;padding:20px}.form-card h3{margin:0 0 4px}.form-card>p{margin:0 0 18px;color:var(--muted);font-size:12px}.field{margin-top:15px}.field label{display:block;font-size:12px;color:#c9ccd4;font-weight:650;margin-bottom:7px}.field input[type=text],.field textarea{width:100%;border:1px solid var(--line);border-radius:9px;background:#181a22;color:var(--text);padding:10px 11px;outline:none;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.field textarea{min-height:135px;resize:vertical}.field input:focus,.field textarea:focus{border-color:var(--blue)}.switch-line{display:flex;align-items:center;justify-content:space-between;border:1px solid var(--line);border-radius:10px;padding:12px 13px}.switch-copy b{display:block}.switch-copy small{color:var(--muted)}.switch{position:relative;width:42px;height:23px}.switch input{opacity:0;width:0;height:0}.slider{position:absolute;inset:0;background:#484c59;border-radius:99px;cursor:pointer}.slider:before{content:"";position:absolute;width:17px;height:17px;left:3px;top:3px;border-radius:50%;background:#fff;transition:.18s}.switch input:checked+.slider{background:var(--blue)}.switch input:checked+.slider:before{transform:translateX(19px)}.form-actions{display:flex;gap:9px;margin-top:17px}.help-card{background:var(--surface);border:1px solid #30333e;border-radius:13px;padding:19px;height:max-content}.help-item{padding:12px 0;border-bottom:1px solid var(--line)}.help-item:last-child{border:0}.help-item b{display:block;font-size:12px}.help-item p{margin:3px 0 0;color:var(--muted);font-size:11px}.config-card{background:var(--surface);border:1px solid #30333e;border-radius:13px;overflow:hidden}.config-meta{display:flex;gap:9px;flex-wrap:wrap}.config-code{margin:0;padding:18px;max-height:calc(100vh - 190px);overflow:auto;background:#15171e;color:#c5d5e7;font:12px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;tab-size:2}.toast{position:fixed;right:22px;bottom:22px;max-width:min(390px,calc(100% - 44px));background:#244233;border:1px solid #477a5d;color:#dcffe8;border-radius:10px;padding:11px 14px;box-shadow:0 18px 50px #0007;opacity:0;transform:translateY(12px);pointer-events:none;transition:.2s;z-index:20}.toast.show{opacity:1;transform:none}.toast.error{background:#482a31;border-color:#84434f;color:#ffd8dc}
    @media(max-width:1050px){.app{grid-template-columns:205px minmax(0,1fr)}.hero,.sync,.traffic,.operations{grid-column:span 12}.proxy-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:720px){body{overflow:auto}.app{height:auto;min-height:100%;display:block}.sidebar{position:sticky;top:0;z-index:10;padding:10px 12px;display:flex;flex-direction:row;align-items:center;border-right:0;border-bottom:1px solid var(--line)}.brand{padding:0;margin-right:auto}.brand-meta,.sidebar-bottom{display:none}.nav{display:flex;gap:3px}.nav-button{width:42px;height:40px;padding:0;display:grid;place-items:center}.nav-button span{display:none}.nav-spacer{display:none}.workspace{min-height:calc(100vh - 61px)}.topbar{height:72px;padding:0 16px}.status-pill{display:none}.content{padding:15px 12px 35px}.metrics{grid-template-columns:1fr 1fr}.proxy-grid{grid-template-columns:1fr}.settings-layout{grid-template-columns:1fr}.page-title{font-size:19px}.hero-body{align-items:flex-start}.hero-proxy{max-width:50%}}
    @media(max-width:440px){.brand-name{display:none}.metrics{grid-template-columns:1fr}.top-actions .button{display:none}.top-actions .icon-button{display:grid}.sync-row{grid-template-columns:82px minmax(0,1fr)}}
  </style>
</head>
<body>
<div class="app">
  <aside class="sidebar">
    <div class="brand"><div class="brand-mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 15c2.5-5 5-7.5 8-7.5S17.5 10 20 15"/><path d="M6 15.5c1.8 2.2 3.8 3.2 6 3.2s4.2-1 6-3.2"/><path d="M8 8 6.7 4.8 10 7M16 8l1.3-3.2L14 7"/></svg></div><div><div class="brand-name">sb-easy</div><div class="brand-meta">Agent Console</div></div></div>
    <nav class="nav">
      <button class="nav-button active" data-view="overview"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 11 12 3l9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/></svg><span>总览</span></button>
      <button class="nav-button" data-view="proxies"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12a7 7 0 0 1 14 0"/><path d="M8 12a4 4 0 0 1 8 0M12 12v1M5 17h14"/></svg><span>代理</span></button>
      <div class="nav-spacer"></div>
      <button class="nav-button" data-view="settings"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/></svg><span>本机设置</span></button>
      <button class="nav-button" data-view="config"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 3h9l4 4v14H6z"/><path d="M14 3v5h5M9 13h7M9 17h7"/></svg><span>运行配置</span></button>
    </nav>
    <div class="sidebar-bottom"><div class="node-line"><i id="side-dot" class="node-dot"></i><div><div id="side-state" class="node-name">正在连接</div><div class="node-caption">本地 sing-box</div></div></div><div class="mini-traffic"><div class="mini-stat">↑ 上传<b id="side-up">—</b></div><div class="mini-stat">↓ 下载<b id="side-down">—</b></div></div><button class="logout" data-logout>退出登录</button></div>
  </aside>
  <section class="workspace">
    <header class="topbar"><div><div id="page-title" class="page-title">总览</div><div id="page-subtitle" class="page-subtitle">Agent 实时状态与流量</div></div><div class="top-actions"><div class="status-pill"><i id="top-dot" class="node-dot"></i><span id="top-state">连接中</span></div><button id="sync-now" class="button primary">立即同步</button><button id="reload-page" class="icon-button" title="刷新页面数据"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg></button><button class="icon-button" data-logout title="退出登录"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 17l5-5-5-5M15 12H3"/><path d="M14 3h6a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-6"/></svg></button></div></header>
    <main class="content">
      <section class="page active" data-page="overview">
        <div class="grid">
          <article class="card hero"><div class="card-head"><div class="card-title"><span class="card-title-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12a7 7 0 0 1 14 0"/><path d="M8 12a4 4 0 0 1 8 0M12 12v1"/></svg></span>当前节点</div><span id="agent-version" class="card-note">—</span></div><div class="hero-body"><div class="hero-state"><div id="hero-icon" class="hero-icon offline"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 13 4 4L19 7"/></svg></div><div><div class="hero-label">sing-box 状态</div><div id="hero-state" class="hero-value">等待状态</div></div></div><div class="hero-proxy"><div class="hero-label">默认代理</div><strong id="current-proxy">尚未加载</strong><span id="current-type" class="type-chip">—</span></div></div></article>
          <article class="card sync"><div class="card-head"><div class="card-title"><span class="card-title-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg></span>配置同步</div><span id="pending-state" class="card-note">空闲</span></div><div class="sync-list"><div class="sync-row"><span>中心服务</span><b id="server-address">—</b></div><div class="sync-row"><span>最近同步</span><b id="last-cycle">—</b></div><div class="sync-row"><span>配置指纹</span><code id="config-etag">—</code></div></div></article>
          <div class="metrics"><div class="metric"><span class="metric-icon up"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 10 6-6 6 6M12 4v16"/></svg></span><div><div class="metric-label">实时上传</div><div id="metric-up" class="metric-value">—</div></div></div><div class="metric"><span class="metric-icon down"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 14 6 6 6-6M12 20V4"/></svg></span><div><div class="metric-label">实时下载</div><div id="metric-down" class="metric-value">—</div></div></div><div class="metric"><span class="metric-icon conn"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7l1-1"/></svg></span><div><div class="metric-label">活跃连接</div><div id="metric-connections" class="metric-value">—</div></div></div><div class="metric"><span class="metric-icon total"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19V9M10 19V5M16 19v-7M22 19V3"/></svg></span><div><div class="metric-label">累计流量</div><div id="metric-total" class="metric-value">—</div></div></div></div>
          <article class="card traffic"><div class="card-head"><div class="card-title"><span class="card-title-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 17l5-5 4 4 8-9"/></svg></span>实时流量</div><span id="telemetry-state" class="card-note">等待 Clash API 数据</span></div><div class="chart-wrap"><div class="chart-legend"><span><i class="legend-dot" style="background:var(--orange)"></i>上传</span><span><i class="legend-dot" style="background:var(--blue)"></i>下载</span></div><canvas id="traffic-chart"></canvas></div></article>
          <article class="card operations"><div class="card-head"><div class="card-title"><span class="card-title-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v10M7 4.5a9 9 0 1 0 10 0"/></svg></span>运行控制</div></div><div class="operation-list"><div class="operation"><div><strong>重新拉取配置</strong><small>忽略 ETag 并安全应用</small></div><button class="button" data-action="refresh">执行</button></div><div class="operation"><div><strong>Reload</strong><small>向 sing-box 发送重载</small></div><button class="button" data-action="reload">执行</button></div><div class="operation"><div><strong>Restart</strong><small>完整重启本地进程</small></div><button class="button danger" data-action="restart">执行</button></div></div></article>
          <div id="last-error" class="error-banner"></div>
        </div>
      </section>
      <section class="page" data-page="proxies"><div class="section-toolbar"><div class="section-copy"><h2>代理节点</h2><p><span id="proxy-count">0</span> 个已写入当前运行配置的出站</p></div><input id="proxy-search" class="search" placeholder="搜索 tag 或协议类型"></div><div id="proxy-grid" class="proxy-grid"></div></section>
      <section class="page" data-page="settings"><div class="section-toolbar"><div class="section-copy"><h2>本机设置</h2><p>仅影响当前 Agent，保存后重新拉取并校验服务端配置</p></div></div><div class="settings-layout"><div class="form-card"><h3>本地出站调整</h3><p>所有值持久化到 agent-data，不会修改或显示 Agent token。</p><div class="switch-line"><div class="switch-copy"><b>使用本机代理出口</b><small>移除代理节点上的管理隧道 detour</small></div><label class="switch"><input id="local-egress" type="checkbox"><span class="slider"></span></label></div><div class="field"><label for="default-outbound">默认代理出站 tag</label><input id="default-outbound" type="text" placeholder="留空则沿用服务端配置"></div><div class="field"><label for="server-overrides">服务器地址覆盖（tag → server）</label><textarea id="server-overrides" spellcheck="false">{}</textarea></div><div class="field"><label for="outbound-overrides">完整出站覆盖（tag → outbound）</label><textarea id="outbound-overrides" spellcheck="false">{}</textarea></div><div class="form-actions"><button id="save-settings" class="button primary">保存并应用</button><button id="reset-settings" class="button">恢复已保存内容</button></div></div><aside class="help-card"><div class="card-title">配置说明</div><div class="help-item"><b>默认代理</b><p>必须是服务端 selector 已包含的出站 tag，否则 sing-box 校验会拒绝应用。</p></div><div class="help-item"><b>服务器地址覆盖</b><p>只替换指定节点的 server 字段，适合本机 DNS 或入口差异。</p></div><div class="help-item"><b>完整出站覆盖</b><p>用完整 JSON outbound 替换节点，可用于接入本地 SOCKS 等特殊出口。</p></div><div class="help-item"><b>安全应用</b><p>设置采用原子持久化；新配置验证失败时不会覆盖当前可用配置。</p></div></aside></div></section>
      <section class="page" data-page="config"><div class="section-toolbar"><div class="section-copy"><h2>当前运行配置</h2><p>来自本机生成文件，可能包含代理凭据，请谨慎复制</p></div><div class="config-meta"><span id="config-outbounds" class="tag-chip">0 outbounds</span><span id="config-rules" class="tag-chip">0 rules</span><button id="copy-config" class="button">复制 JSON</button></div></div><div class="config-card"><pre id="config-code" class="config-code">加载中…</pre></div></section>
    </main>
  </section>
</div>
<div id="toast" class="toast"></div>
<script>
const $=id=>document.getElementById(id);const state={status:null,settings:null,proxies:[],config:{},traffic:[],lastTelemetrySample:null};let toastTimer=null;
const pages={overview:['总览','Agent 实时状态与流量'],proxies:['代理','当前运行配置中的出站节点'],settings:['本机设置','节点本地覆盖与安全应用'],config:['运行配置','当前 sing-box JSON 配置']};
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='toast',3500)}
async function api(path,options={}){const response=await fetch(path,{cache:'no-store',...options,headers:{Accept:'application/json','X-SB-Easy-UI':'1',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});if(response.status===401){location.replace('/login');throw new Error('登录已失效')}const raw=await response.text();let body={};try{body=raw?JSON.parse(raw):{}}catch{body={error:raw}}if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body}
function switchView(view){document.querySelectorAll('.nav-button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.dataset.page===view));$('page-title').textContent=pages[view][0];$('page-subtitle').textContent=pages[view][1];if(view==='config')$('config-code').textContent=JSON.stringify(state.config,null,2);if(view==='overview')requestAnimationFrame(drawChart)}
document.querySelectorAll('.nav-button').forEach(el=>el.onclick=()=>switchView(el.dataset.view));
function formatBytes(value,rate=false){let number=Number(value||0);const units=['B','KB','MB','GB','TB'];let index=0;while(number>=1024&&index<units.length-1){number/=1024;index++}const digits=number>=100||index===0?0:number>=10?1:2;return `${number.toFixed(digits)} ${units[index]}${rate?'/s':''}`}
function formatTime(value){if(!value)return '等待首次同步';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString()}
function shortEtag(value){if(!value)return '尚未获取';return value.length>28?value.slice(0,14)+'…'+value.slice(-10):value}
function currentProxy(){return state.proxies.find(proxy=>proxy.default)||null}
function updateStatus(){const s=state.status||{},running=s.running===true,t=s.telemetry||{};['side-dot','top-dot'].forEach(id=>$(id).classList.toggle('online',running));$('side-state').textContent=running?'运行中':'需要检查';$('top-state').textContent=running?'Agent 正常':'Agent 异常';$('hero-icon').classList.toggle('offline',!running);$('hero-state').textContent=running?'sing-box 运行中':s.running==null?'状态未知':'sing-box 已停止';$('agent-version').textContent=s.version?`v${s.version}`:'—';$('server-address').textContent=s.server||'—';$('server-address').title=s.server||'';$('last-cycle').textContent=formatTime(s.last_cycle);$('config-etag').textContent=shortEtag(s.etag);$('config-etag').title=s.etag||'';const pending=s.pending||{},pendingNames=Object.entries(pending).filter(([,value])=>value).map(([name])=>name);$('pending-state').textContent=pendingNames.length?`等待 ${pendingNames.join(', ')}`:'空闲';$('metric-up').textContent=t.available?formatBytes(t.up,true):'等待数据';$('metric-down').textContent=t.available?formatBytes(t.down,true):'等待数据';$('metric-connections').textContent=t.available?String(t.conn_count||0):'—';$('metric-total').textContent=t.available?formatBytes(Number(t.up_total||0)+Number(t.down_total||0)):'—';$('side-up').textContent=t.available?formatBytes(t.up,true):'—';$('side-down').textContent=t.available?formatBytes(t.down,true):'—';$('telemetry-state').textContent=t.available?'来自本地 Clash API':'等待 Clash API 数据';const error=$('last-error');error.textContent=s.last_error?'最近错误：'+s.last_error:'';error.classList.toggle('show',!!s.last_error);const current=currentProxy();$('current-proxy').textContent=current?current.tag:'未找到默认代理';$('current-proxy').title=current?.tag||'';$('current-type').textContent=current?.type||'—';if(t.available&&t.sampled_at!==state.lastTelemetrySample){state.lastTelemetrySample=t.sampled_at;state.traffic.push({up:Number(t.up||0),down:Number(t.down||0)});if(state.traffic.length>60)state.traffic.shift();drawChart()}}
function drawChart(){const canvas=$('traffic-chart');if(!canvas||!canvas.offsetWidth)return;const ratio=Math.min(devicePixelRatio||1,2),width=canvas.offsetWidth,height=canvas.offsetHeight;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);const pad={l:8,r:8,t:28,b:17},plotW=width-pad.l-pad.r,plotH=height-pad.t-pad.b;ctx.strokeStyle='#353945';ctx.lineWidth=1;for(let row=0;row<4;row++){const y=pad.t+plotH*row/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke()}const values=state.traffic.length?state.traffic:[{up:0,down:0}],max=Math.max(1,...values.flatMap(point=>[point.up,point.down]));function line(field,color,fill){ctx.beginPath();values.forEach((point,index)=>{const x=pad.l+(values.length===1?0:plotW*index/(values.length-1)),y=pad.t+plotH-(point[field]/max)*plotH;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();if(values.length>1){ctx.lineTo(width-pad.r,pad.t+plotH);ctx.lineTo(pad.l,pad.t+plotH);ctx.closePath();const gradient=ctx.createLinearGradient(0,pad.t,0,pad.t+plotH);gradient.addColorStop(0,fill);gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.fill()}}line('down','#4d8ff7','#4d8ff733');line('up','#f5a742','#f5a74222');ctx.fillStyle='#858a97';ctx.font='10px system-ui';ctx.fillText(formatBytes(max,true),pad.l,pad.t-10);ctx.fillText('最近 '+values.length+' 次采样',pad.l,height-2)}
function renderProxies(){const query=$('proxy-search').value.trim().toLowerCase(),filtered=state.proxies.filter(proxy=>(proxy.tag+' '+proxy.type).toLowerCase().includes(query));$('proxy-count').textContent=String(state.proxies.length);$('proxy-grid').innerHTML=filtered.length?filtered.map(proxy=>`<article class="proxy-card ${proxy.default?'current':''}"><div class="proxy-top"><div class="proxy-avatar">${escapeHtml((proxy.tag||'?').trim().slice(0,1).toUpperCase())}</div>${proxy.default?'<span class="current-mark">● 当前</span>':'<span class="tag-chip">已配置</span>'}</div><div class="proxy-name" title="${escapeHtml(proxy.tag)}">${escapeHtml(proxy.tag)}</div><div class="proxy-meta"><span>${escapeHtml(proxy.type||'unknown')}</span><span>${proxy.default?'默认出站':'可用出站'}</span></div></article>`).join(''):'<div class="empty">没有匹配的代理节点</div>';updateStatus()}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function loadSettingsForm(){const value=state.settings||{};$('local-egress').checked=!!value.local_proxy_egress;$('default-outbound').value=value.default_proxy_outbound||'';$('server-overrides').value=JSON.stringify(value.outbound_server_overrides||{},null,2);$('outbound-overrides').value=JSON.stringify(value.outbound_overrides||{},null,2)}
function formSettings(){let servers,outbounds;try{servers=JSON.parse($('server-overrides').value||'{}')}catch(error){throw new Error('服务器地址覆盖不是有效 JSON：'+error.message)}try{outbounds=JSON.parse($('outbound-overrides').value||'{}')}catch(error){throw new Error('完整出站覆盖不是有效 JSON：'+error.message)}return{local_proxy_egress:$('local-egress').checked,default_proxy_outbound:$('default-outbound').value.trim()||null,outbound_server_overrides:servers,outbound_overrides:outbounds}}
function updateConfigMeta(){const outbounds=Array.isArray(state.config.outbounds)?state.config.outbounds.length:0,rules=Array.isArray(state.config.route?.rules)?state.config.route.rules.length:0;$('config-outbounds').textContent=`${outbounds} outbounds`;$('config-rules').textContent=`${rules} rules`;$('config-code').textContent=JSON.stringify(state.config,null,2)}
async function loadStatus(){try{state.status=await api('/api/status');updateStatus()}catch(error){toast(error.message,true)}}
async function loadAll(){try{const [settings,proxies,config,status]=await Promise.all([api('/api/settings'),api('/api/proxies'),api('/api/config'),api('/api/status')]);state.settings=settings;state.proxies=Array.isArray(proxies)?proxies:[];state.config=config||{};state.status=status;loadSettingsForm();renderProxies();updateConfigMeta();updateStatus()}catch(error){toast(error.message,true)}}
$('proxy-search').oninput=renderProxies;$('reload-page').onclick=async()=>{await loadAll();toast('页面数据已刷新')};$('sync-now').onclick=async event=>{event.currentTarget.disabled=true;try{await api('/api/actions/refresh',{method:'POST'});toast('配置同步已排队');setTimeout(loadAll,1200)}catch(error){toast(error.message,true)}finally{event.currentTarget.disabled=false}};
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/api/actions/'+button.dataset.action,{method:'POST'});toast('操作已排队：'+button.dataset.action);setTimeout(loadAll,1200)}catch(error){toast(error.message,true)}finally{button.disabled=false}});
$('save-settings').onclick=async()=>{const button=$('save-settings');button.disabled=true;try{state.settings=await api('/api/settings',{method:'PUT',body:JSON.stringify(formSettings())});loadSettingsForm();toast('设置已保存，配置同步已排队');setTimeout(loadAll,1400)}catch(error){toast(error.message,true)}finally{button.disabled=false}};$('reset-settings').onclick=loadSettingsForm;
async function copyText(value){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return}catch{}}const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw new Error('copy failed')}
$('copy-config').onclick=async()=>{try{await copyText(JSON.stringify(state.config,null,2));toast('配置 JSON 已复制')}catch{toast('浏览器不允许访问剪贴板',true)}};document.querySelectorAll('[data-logout]').forEach(button=>button.onclick=async()=>{try{await api('/api/logout',{method:'POST'})}finally{location.replace('/login')}});addEventListener('resize',()=>requestAnimationFrame(drawChart));
loadAll();setInterval(loadStatus,3000);
</script>
</body>
</html>)HTML";

} // namespace sbeasy::detail
